/**
 * Reji Fashions - Product Catalog Data & Visual Generation Engine
 * Handcrafted ethnic wear: Churidars, Kurtis, Anarkalis & Fusion sets.
 */

const REJI_PRODUCTS = [
  {
    id: "RF-K01",
    name: "Aaradhya Handblock Chanderi Silk Kurti",
    tagline: "Woven in pure Chanderi with handcrafted antique gold Zari yoke",
    category: "kurtis",
    subCategory: "Straight Cut Kurti",
    price: 2499,
    originalPrice: 3499,
    discount: "29% OFF",
    rating: 4.9,
    reviewsCount: 128,
    color: "Wine Maroon & Gold",
    colorHex: "#5A1322",
    accentHex: "#D4AF37",
    fabric: "Chanderi Silk",
    fabricCategory: "Silk",
    occasion: "Festive / Evening",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: 7,
    isBestseller: true,
    isNew: false,
    featured: true,
    badge: "Bestseller",
    description: "The Aaradhya Kurti is an epitome of regal grace, featuring pure handblock printed Chanderi silk with an intricately embroidered antique gold zari yoke. Designed with a Mandarin collar and 3/4 sleeves adorned with delicate gota patti finishing. Pairs effortlessly with raw silk pants or classic churidars.",
    details: {
      "Kurti Style": "Straight cut with side slits",
      "Fabric Composition": "80% Pure Chanderi Silk, 20% Cotton Silk Lining",
      "Neckline": "Keyhole Mandarin with Hand Embroidery",
      "Sleeve Length": "3/4th with Gota Border (17 inches)",
      "Kurti Length": "46 inches (Calf length)",
      "Care Instructions": "Dry clean only for initial wash. Gentle hand wash thereafter."
    },
    inTheBox: "1 Handcrafted Chanderi Kurti (Inner lining attached)",
    visualType: "chanderi_maroon"
  },
  {
    id: "RF-K02",
    name: "Noor Gulabi Pure Mulmul Cotton Kurti",
    tagline: "Ultra-breathable Jaipur floral block print with shell button accents",
    category: "kurtis",
    subCategory: "A-Line Daily Kurti",
    price: 1299,
    originalPrice: 1799,
    discount: "28% OFF",
    rating: 4.8,
    reviewsCount: 94,
    color: "Blush Rose & Ivory",
    colorHex: "#D87080",
    accentHex: "#FFF5F5",
    fabric: "Pure Mulmul Cotton",
    fabricCategory: "Cotton",
    occasion: "Casual / Workwear",
    sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
    stock: 14,
    isBestseller: false,
    isNew: true,
    featured: true,
    badge: "New Arrival",
    description: "Handcrafted from 100% fine Jaipur mulmul cotton, the Noor Gulabi Kurti offers featherlight comfort for long workdays and casual outings. Hand-stamped with natural vegetable dyes in artisanal floral motifs and tailored with a subtle A-line silhouette.",
    details: {
      "Kurti Style": "Gentle A-Line Flare with pocket",
      "Fabric Composition": "100% Organic Mulmul Cotton",
      "Neckline": "Sweetheart V-Neck with Mother-of-Pearl buttons",
      "Sleeve Length": "Roll-up 3/4 Sleeves with button tab",
      "Kurti Length": "44 inches",
      "Care Instructions": "Machine wash cold with like colors. Dry in shade."
    },
    inTheBox: "1 Jaipur Handblock Mulmul Kurti",
    visualType: "mulmul_pink"
  },
  {
    id: "RF-K03",
    name: "Meera Royal Emerald Resham Embroidered Kurti",
    tagline: "Lustrous peacock emerald with intricate silver and gold Resham flora",
    category: "kurtis",
    subCategory: "Embroidered Straight Kurti",
    price: 1899,
    originalPrice: 2699,
    discount: "30% OFF",
    rating: 4.9,
    reviewsCount: 156,
    color: "Royal Emerald Peacock",
    colorHex: "#0D4239",
    accentHex: "#C59B27",
    fabric: "Silk Blend Rayon",
    fabricCategory: "Silk Blend",
    occasion: "Festive / Puja",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: 4,
    isBestseller: true,
    isNew: false,
    featured: true,
    badge: "Limited Edition",
    description: "Make an unforgettable statement in the Meera Kurti, saturated in deep peacock emerald green. Features heavy Resham thread embroidery along the front placket, paired with shimmering zari highlights. Rich drape and wrinkle-resistant finish.",
    details: {
      "Kurti Style": "Tailored Straight Fit with contrast piping",
      "Fabric Composition": "Heavy Rayon Silk with Cotton Slub weave",
      "Neckline": "Round neck with split V front",
      "Sleeve Length": "Full sleeves with embroidered cuffs",
      "Kurti Length": "47 inches",
      "Care Instructions": "Dry clean recommended to preserve Resham luster."
    },
    inTheBox: "1 Royal Emerald Embroidered Kurti",
    visualType: "emerald_embroidered"
  },
  {
    id: "RF-K04",
    name: "Zoya Lucknowi Chikankari Mukaish Kurti",
    tagline: "Authentic Lucknow hand embroidery with sparkling metallic Mukaish dots",
    category: "kurtis",
    subCategory: "Chikankari Kurti",
    price: 2199,
    originalPrice: 2999,
    discount: "27% OFF",
    rating: 4.9,
    reviewsCount: 112,
    color: "Pastel Powder Blue",
    colorHex: "#779BB5",
    accentHex: "#FFFFFF",
    fabric: "Pure Georgette",
    fabricCategory: "Georgette",
    occasion: "Casual / Evening",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 9,
    isBestseller: false,
    isNew: true,
    featured: false,
    badge: "Artisanal",
    description: "An authentic masterpiece from Lucknowi artisans, this powder blue georgette kurti showcases intricate Bakhiya, Phanda, and Keel Kangan embroidery, elevated with hand-embedded Mukaish silver sequins.",
    details: {
      "Kurti Style": "Classic Straight Chikankari Cut",
      "Fabric Composition": "Featherlight Viscose Georgette (Includes matching dyed slip)",
      "Neckline": "Round neckline with all-over jaal embroidery",
      "Sleeve Length": "3/4th sheer embroidered sleeves",
      "Kurti Length": "45 inches",
      "Care Instructions": "Hand wash gently in cold water with mild detergent."
    },
    inTheBox: "1 Chikankari Kurti + 1 Dyed Cotton Inner Slip",
    visualType: "chikankari_blue"
  },
  {
    id: "RF-K05",
    name: "Sitara Mirror Work Peplum Short Kurti",
    tagline: "Vibrant festive mustard with authentic reflective mirror work & tassels",
    category: "kurtis",
    subCategory: "Short Peplum Kurti",
    price: 1699,
    originalPrice: 2299,
    discount: "26% OFF",
    rating: 4.7,
    reviewsCount: 81,
    color: "Haldi Mustard Yellow",
    colorHex: "#D99B26",
    accentHex: "#8B0000",
    fabric: "Cotton Silk",
    fabricCategory: "Cotton",
    occasion: "Festive / Haldi",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 6,
    isBestseller: false,
    isNew: false,
    featured: false,
    badge: "Festive Favorite",
    description: "Radiate celebratory sunshine with the Sitara short peplum kurti. Crafted with real glass mirrors stitched in Kutchi geometric borders, pleated waist flare, and artisan dori tassels on the back tie-up.",
    details: {
      "Kurti Style": "Flared Peplum Short Kurti (Ideal with dhoti / sharara)",
      "Fabric Composition": "Pure Cotton Silk Blend",
      "Neckline": "Angrakha overlap with mirror trim",
      "Sleeve Length": "Elbow length sleeves with mirror borders",
      "Kurti Length": "32 inches",
      "Care Instructions": "Dry clean only."
    },
    inTheBox: "1 Peplum Kurti with artisan tassels",
    visualType: "mustard_mirror"
  },
  {
    id: "RF-K06",
    name: "Kashvi Banarasi Brocade Flared Anarkali Kurti",
    tagline: "Regal wine brocade with heavy gold zari weave and 3-meter sweeping ghera",
    category: "kurtis",
    subCategory: "Anarkali Kurti",
    price: 3299,
    originalPrice: 4799,
    discount: "31% OFF",
    rating: 5.0,
    reviewsCount: 204,
    color: "Imperial Wine & Antique Gold",
    colorHex: "#48101E",
    accentHex: "#E5C07B",
    fabric: "Banarasi Brocade Silk",
    fabricCategory: "Silk",
    occasion: "Wedding / Party",
    sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
    stock: 3,
    isBestseller: true,
    isNew: true,
    featured: true,
    badge: "Royal Collection",
    description: "The crown jewel of ethnic craftsmanship. The Kashvi Anarkali combines 24 kalis of pure Banarasi gold brocade with a structured sweetheart bodice, creating a grand royal silhouette for weddings and galas.",
    details: {
      "Kurti Style": "24-Kali Flared Anarkali (3.5m circumference)",
      "Fabric Composition": "Banarasi Katan Silk with heavy micro-lining",
      "Neckline": "Sweetheart neckline with zari piping",
      "Sleeve Length": "Fitted full sleeves (Churidar sleeves)",
      "Kurti Length": "52 inches (Floor length touch)",
      "Care Instructions": "Strictly Dry Clean Only."
    },
    inTheBox: "1 Banarasi Brocade Anarkali Kurti with padded cups & side zipper",
    visualType: "banarasi_anarkali"
  },

  // CHURIDAR & SALWAR SUIT SETS
  {
    id: "RF-C01",
    name: "Maharani Velvet Embroidered Bridal Churidar Set",
    tagline: "3-Piece Masterpiece: Royal Burgundy Velvet Kurta, Churidar Pants & Zardozi Organza Dupatta",
    category: "churidars",
    subCategory: "Bridal Churidar Suit",
    price: 6499,
    originalPrice: 8999,
    discount: "28% OFF",
    rating: 5.0,
    reviewsCount: 189,
    color: "Royal Burgundy Wine",
    colorHex: "#3F0A15",
    accentHex: "#F3E5AB",
    fabric: "Micro Velvet & Pure Organza",
    fabricCategory: "Velvet",
    occasion: "Wedding / Party",
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "Custom Fit"],
    stock: 5,
    isBestseller: true,
    isNew: true,
    featured: true,
    badge: "Bridal Couture",
    description: "Indulge in royal grandeur with the Maharani Bridal Set. Features a plush micro-velvet kurta adorned with authentic Mughal Dabka, Zardozi, and sequence hand embroidery. Complete with stretch-churidar pants with gathered gathers and a 2.5m scalloped sheer organza dupatta.",
    details: {
      "Set Contents": "1 Velvet Kurta + 1 Lycra Cotton Churidar + 1 Scalloped Dupatta",
      "Kurta Fabric": "Premium Royal Micro Velvet (Heavy weight, feather-soft)",
      "Bottom Fabric": "Stretchable Cotton Lycra Churidar with 18 gathers",
      "Dupatta": "2.5m Pure Silk Organza with cutwork Zardozi borders",
      "Neckline": "Deep V-neck with handcrafted potli buttons",
      "Tailoring": "Fully finished with satin lining & bra-snaps",
      "Care Instructions": "Specialist Dry Clean Only."
    },
    inTheBox: "1 Heavy Velvet Kurta, 1 Churidar Pant, 1 Embroidered Organza Dupatta",
    visualType: "velvet_churidar"
  },
  {
    id: "RF-C02",
    name: "Devika Banarasi Brocade Churidar Suit with Tissue Dupatta",
    tagline: "3-Piece Festive Set: Peacock Teal Brocade Kurti, Butter Silk Churidar & Gold Tissue Dupatta",
    category: "churidars",
    subCategory: "Festive Churidar Suit",
    price: 5299,
    originalPrice: 7199,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 142,
    color: "Peacock Teal & Gold",
    colorHex: "#0B3C38",
    accentHex: "#D4AF37",
    fabric: "Banarasi Katan Silk",
    fabricCategory: "Silk",
    occasion: "Festive / Wedding",
    sizes: ["S", "M", "L", "XL", "XXL", "Custom Fit"],
    stock: 8,
    isBestseller: true,
    isNew: false,
    featured: true,
    badge: "Heritage Silk",
    description: "Woven in the historic looms of Varanasi, the Devika Churidar Suit features intricate shikargah hunting motifs in metallic gold and copper zari. Paired with a shimmering golden tissue dupatta with hand-knotted silk tassels.",
    details: {
      "Set Contents": "1 Brocade Kurta + 1 Butter Silk Churidar + 1 Tissue Silk Dupatta",
      "Kurta Fabric": "Pure Banarasi Katan Weave with butter-crepe lining",
      "Bottom": "Raw Silk blend Churidar with elastic & drawstring closure",
      "Dupatta": "2.4m Metallic Lurex Tissue Dupatta with Zari borders",
      "Sleeve Style": "Fitted 3/4 sleeves with brocade border",
      "Care Instructions": "Dry clean only. Iron on reverse with low heat."
    },
    inTheBox: "1 Brocade Kurti, 1 Silk Churidar Bottom, 1 Gold Tissue Dupatta",
    visualType: "teal_brocade_churidar"
  },
  {
    id: "RF-C03",
    name: "Aanya Scalloped Organza Floral Churidar Set",
    tagline: "3-Piece Ensemble: Pastel Sage Green Kurti, Pearl Churidar & Hand-painted Organza Dupatta",
    category: "churidars",
    subCategory: "Floral Churidar Set",
    price: 3899,
    originalPrice: 5199,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 97,
    color: "Pastel Sage Green",
    colorHex: "#6F8F7E",
    accentHex: "#F2EBE5",
    fabric: "Pure Organza & Modal Silk",
    fabricCategory: "Organza",
    occasion: "Festive / Day Events",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 6,
    isBestseller: false,
    isNew: true,
    featured: false,
    badge: "Pastel Elegance",
    description: "Embrace ethereal charm with the Aanya Churidar Set. Delicate botanical florals hand-painted on sheer organza, accented with subtle pearl embellishments and finished with scalloped laser-cut borders.",
    details: {
      "Set Contents": "1 Organza Kurti + 1 Cotton Modal Churidar + 1 Hand-painted Dupatta",
      "Kurta Fabric": "Pure Organza with dyed Mulberry Silk under-layer",
      "Bottom": "Soft Modal Churidar with comfort stretch",
      "Dupatta": "2.5m Floral Organza Dupatta with pearl droplet edging",
      "Neckline": "Sweetheart Neckline with scalloped organza overlay",
      "Care Instructions": "Dry clean only."
    },
    inTheBox: "1 Floral Organza Kurti, 1 Modal Churidar, 1 Scalloped Dupatta",
    visualType: "sage_organza_churidar"
  },
  {
    id: "RF-C04",
    name: "Roshni Pure Chanderi Cutwork Churidar Set",
    tagline: "3-Piece Festive Set: Luxe Ivory Chanderi Kurti, Gota Churidar & Rose Gold Dupatta",
    category: "churidars",
    subCategory: "Chanderi Churidar Set",
    price: 4499,
    originalPrice: 5999,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 118,
    color: "Luxe Ivory & Rose Gold",
    colorHex: "#FAF6EE",
    accentHex: "#B76E79",
    fabric: "Chanderi Silk",
    fabricCategory: "Silk",
    occasion: "Festive / Puja",
    sizes: ["S", "M", "L", "XL", "XXL", "Custom Fit"],
    stock: 7,
    isBestseller: true,
    isNew: false,
    featured: true,
    badge: "Chanderi Weave",
    description: "The Roshni Chanderi Set radiates refined elegance with its pristine ivory base woven with subtle copper and rose gold zari threads. Features precision cutwork hemline and coordinated churidar with extra length for beautiful pleat stacking.",
    details: {
      "Set Contents": "1 Chanderi Kurti + 1 Cotton Silk Churidar + 1 Jacquard Dupatta",
      "Kurta Fabric": "Handwoven Chanderi Pattu with cotton lining",
      "Bottom": "Pure Cotton Silk Churidar (55 inches length for 14-inch churi stack)",
      "Dupatta": "2.4m Rose Gold Zari Jacquard Chanderi Dupatta",
      "Neckline": "Angrakha cross neckline with rose gold piping",
      "Care Instructions": "Gentle dry clean only."
    },
    inTheBox: "1 Ivory Chanderi Kurti, 1 Churidar Pant, 1 Rose Gold Dupatta",
    visualType: "ivory_chanderi_churidar"
  },
  {
    id: "RF-C05",
    name: "Vaidehi Angrakha Gota Patti Churidar Set",
    tagline: "3-Piece Festive Set: Sunset Crimson & Coral Kurti with Traditional Rajasthani Gota Jaal",
    category: "churidars",
    subCategory: "Angrakha Churidar Suit",
    price: 3699,
    originalPrice: 4899,
    discount: "24% OFF",
    rating: 4.8,
    reviewsCount: 86,
    color: "Crimson Red & Sunset Coral",
    colorHex: "#991B1B",
    accentHex: "#F59E0B",
    fabric: "Georgette Silk",
    fabricCategory: "Georgette",
    occasion: "Festive / Karva Chauth",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: 5,
    isBestseller: false,
    isNew: true,
    featured: false,
    badge: "Gota Patti",
    description: "A tribute to Rajasthani royal heritage, the Vaidehi suit features authentic beaten gota patti floral motifs stitched across an asymmetric Angrakha overlap with handcrafted latkans and festive churidar bottoms.",
    details: {
      "Set Contents": "1 Angrakha Kurti + 1 Stretch Churidar + 1 Leheriya Dupatta",
      "Kurta Fabric": "Flowing Viscose Georgette with Shantoon lining",
      "Bottom": "Super-soft stretch cotton Churidar",
      "Dupatta": "2.5m Vibrant Rajasthani Leheriya Dupatta with Gota Kiran",
      "Neckline": "Overlapping V-Angrakha with tie-up latkans",
      "Care Instructions": "Dry clean only."
    },
    inTheBox: "1 Angrakha Kurti, 1 Churidar, 1 Leheriya Dupatta",
    visualType: "crimson_angrakha_churidar"
  },
  {
    id: "RF-C06",
    name: "Anvi Mulmul Indigo Block Print Churidar Set",
    tagline: "3-Piece Casual Set: Deep Indigo Dabu Block Kurti, White Churidar & Mulmul Dupatta",
    category: "churidars",
    subCategory: "Cotton Salwar Set",
    price: 2299,
    originalPrice: 2999,
    discount: "23% OFF",
    rating: 4.9,
    reviewsCount: 165,
    color: "Indigo Blue & White",
    colorHex: "#1E3A8A",
    accentHex: "#F8FAFC",
    fabric: "Pure Mulmul Cotton",
    fabricCategory: "Cotton",
    occasion: "Casual / Workwear",
    sizes: ["S", "M", "L", "XL", "XXL", "3XL"],
    stock: 12,
    isBestseller: true,
    isNew: false,
    featured: false,
    badge: "Daily Luxury",
    description: "Crafted using heritage mud-resist Dabu block printing techniques with natural indigo vats. Extremely light, breathable, and designed for supreme all-day comfort without sacrificing traditional grace.",
    details: {
      "Set Contents": "1 Indigo Kurti + 1 Pure Cotton Churidar + 1 Sheer Mulmul Dupatta",
      "Kurta Fabric": "100% Bagru Dabu Printed Mulmul Cotton",
      "Bottom": "Fine count cotton churidar with adjustable waistband",
      "Dupatta": "2.5m Full width Mulmul Stole Dupatta",
      "Neckline": "Boat neck with button placket",
      "Care Instructions": "First wash dry clean. Subsequent washes cold machine wash with mild detergent."
    },
    inTheBox: "1 Indigo Kurti, 1 White Cotton Churidar, 1 Printed Dupatta",
    visualType: "indigo_cotton_churidar"
  },

  // INDO-WESTERN & CO-ORDS
  {
    id: "RF-F01",
    name: "Tara Embroidered Cape & Dhoti Kurti Set",
    tagline: "2-Piece Indo-Western Set: Navy Blue Embroidered Cape Kurti with Pleated Dhoti Pants",
    category: "fusion",
    subCategory: "Indo-Western Set",
    price: 4199,
    originalPrice: 5699,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 103,
    color: "Midnight Navy & Copper Zari",
    colorHex: "#0F172A",
    accentHex: "#D97706",
    fabric: "Crepe Silk & Georgette",
    fabricCategory: "Silk Blend",
    occasion: "Party / Sangeet",
    sizes: ["XS", "S", "M", "L", "XL"],
    stock: 4,
    isBestseller: false,
    isNew: true,
    featured: true,
    badge: "Trending Now",
    description: "Modern ethnic styling at its finest. Features a structured crop kurti top with an attached floor-sweeping sheer cape, embroidered in geometric copper zari, paired with pre-stitched cowled dhoti pants.",
    details: {
      "Set Contents": "1 Cape Kurti Top + 1 Ready-to-wear Pleated Dhoti Pant",
      "Fabric": "Heavy Italian Crepe & French Georgette",
      "Dhoti": "Pre-draped fluid dhoti with soft elastic waistband",
      "Cape": "Attached sheer floor-length embroidered overlay",
      "Care Instructions": "Dry clean only."
    },
    inTheBox: "1 Embroidered Cape Kurti, 1 Ready Pleated Dhoti Pant",
    visualType: "navy_cape_dhoti"
  },
  {
    id: "RF-F02",
    name: "Rhea Haldi Saffron Sharara & Kurti Set",
    tagline: "3-Piece Festive Set: Mustard Saffron Kurti with Multi-tiered Sharara & Gota Dupatta",
    category: "fusion",
    subCategory: "Sharara Suit Set",
    price: 4799,
    originalPrice: 6299,
    discount: "24% OFF",
    rating: 5.0,
    reviewsCount: 147,
    color: "Haldi Saffron & Gold",
    colorHex: "#EA580C",
    accentHex: "#FACC15",
    fabric: "Georgette Silk",
    fabricCategory: "Georgette",
    occasion: "Festive / Haldi / Wedding",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: 5,
    isBestseller: true,
    isNew: true,
    featured: true,
    badge: "Wedding Edit",
    description: "A show-stopping ensemble for Haldi and Mehendi festivities. Features a rich saffron yellow kurti with shimmering mirror and gota jaal embroidery, 3-tiered voluminous sharara pants, and a scalloped dupatta.",
    details: {
      "Set Contents": "1 Embroidered Short Kurti + 1 3-Tier Sharara + 1 Gota Dupatta",
      "Fabric": "Pure Viscose Georgette with micro-butter lining",
      "Sharara Girth": "2.8m flare per leg for fluid movement",
      "Dupatta": "2.4m Georgette Dupatta with four-side Kiran lace",
      "Care Instructions": "Dry clean only."
    },
    inTheBox: "1 Short Kurti, 1 Flared Sharara Bottom, 1 Scalloped Dupatta",
    visualType: "saffron_sharara_set"
  },
  {
    id: "RF-F03",
    name: "Ira Contemporary Peplum Kurti with Palazzo",
    tagline: "2-Piece Set: Blush Peach Silk Peplum Kurti with Wide-Leg Embroidered Palazzo",
    category: "fusion",
    subCategory: "Co-ord Set",
    price: 3499,
    originalPrice: 4499,
    discount: "22% OFF",
    rating: 4.8,
    reviewsCount: 78,
    color: "Blush Peach & Pearl",
    colorHex: "#E0938A",
    accentHex: "#FFFBEB",
    fabric: "Modal Silk",
    fabricCategory: "Silk Blend",
    occasion: "Casual / Party",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 8,
    isBestseller: false,
    isNew: false,
    featured: false,
    badge: "Contemporary",
    description: "Effortlessly elegant co-ord set in lustrous modal silk. Designed with a tailored peplum bodice, subtle pleating at the waist, and matching wide-leg palazzos with delicate thread borders.",
    details: {
      "Set Contents": "1 Peplum Kurti + 1 Wide-Leg Palazzo Pants",
      "Fabric": "Natural Modal Silk blend",
      "Palazzo": "Straight wide silhouette with two side pockets",
      "Closure": "Concealed side zipper & back elastic",
      "Care Instructions": "Hand wash gently in cold water or dry clean."
    },
    inTheBox: "1 Peplum Kurti Top, 1 Flared Palazzo Pant",
    visualType: "peach_peplum_palazzo"
  },
  {
    id: "RF-F04",
    name: "Saanvi Linen Silk Asymmetrical Tunic Set",
    tagline: "2-Piece Set: Earthy Rust High-Low Kurti with Narrow Cigarette Pants",
    category: "fusion",
    subCategory: "Fusion Tunic Set",
    price: 2899,
    originalPrice: 3899,
    discount: "25% OFF",
    rating: 4.7,
    reviewsCount: 64,
    color: "Earthy Terracotta Rust",
    colorHex: "#9A3412",
    accentHex: "#FDE68A",
    fabric: "Linen Silk",
    fabricCategory: "Cotton",
    occasion: "Casual / Workwear",
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 11,
    isBestseller: false,
    isNew: false,
    featured: false,
    badge: "Sustainable Wear",
    description: "Modern minimalist silhouette tailored from organic handloom linen silk. Features an architectural high-low curved hemline, wooden artisan buttons, and cropped cigarette trousers.",
    details: {
      "Set Contents": "1 High-Low Tunic Kurti + 1 Cigarette Pants",
      "Fabric": "70% Organic Handloom Linen, 30% Mulberry Silk",
      "Pants": "Ankle length with side slits and elasticated back",
      "Fit": "Relaxed tailored fit",
      "Care Instructions": "Hand wash with eco-friendly detergent. Iron damp."
    },
    inTheBox: "1 Asymmetrical Linen Tunic, 1 Cigarette Trouser",
    visualType: "rust_linen_tunic"
  }
];

// Curated Lookbooks for "Shop the Look"
const REJI_LOOKBOOKS = [
  {
    id: "LB-01",
    title: "Royal Burgundy Wedding Gala",
    subtitle: "Regal Velvet & Zardozi Couture for Autumn Nuptials",
    tag: "Festive Edit 2026",
    heroImageColor: "#3F0A15",
    accentColor: "#D4AF37",
    productIds: ["RF-C01", "RF-K06"],
    curatedNotes: "Pair our heavy Maharani Velvet Churidar with gold temple jewelry and embellished mojris for an unforgettable bridal entourage look."
  },
  {
    id: "LB-02",
    title: "The Chanderi Silk Heritage Edit",
    subtitle: "Timeless Handblock Weaves in Luxe Emerald & Wine",
    tag: "Artisanal Classics",
    heroImageColor: "#0D4239",
    accentColor: "#F3E5AB",
    productIds: ["RF-K01", "RF-K03", "RF-C04"],
    curatedNotes: "Handcrafted Chanderi silk drapes with featherlight comfort, balancing royal heirloom grandeur with day-to-night ease."
  },
  {
    id: "LB-03",
    title: "Sunlit Haldi & Sangeet Soirée",
    subtitle: "Vibrant Saffron Yellows, Gota Patti & Voluminous Shararas",
    tag: "Celebration Special",
    heroImageColor: "#EA580C",
    accentColor: "#FACC15",
    productIds: ["RF-F02", "RF-K05"],
    curatedNotes: "Twirl in festive cheer with 3-tiered flared silhouettes, authentic glass mirror work, and handcrafted leheriya dupattas."
  }
];

// Customer Testimonials
const REJI_REVIEWS = [
  {
    name: "Ananya Deshmukh",
    city: "Mumbai",
    rating: 5,
    verified: true,
    product: "Maharani Velvet Embroidered Bridal Churidar Set",
    text: "The velvet fabric quality is exceptional! The Zardozi work is so intricate and clean. I wore it for my sister's reception and received endless compliments. The custom stitching option fit like a glove!",
    date: "August 2, 2026",
    avatar: "AD"
  },
  {
    name: "Priyanka Nambiar",
    city: "Bengaluru",
    rating: 5,
    verified: true,
    product: "Aaradhya Handblock Chanderi Silk Kurti",
    text: "Reji Fashions has become my go-to ethnic destination. The Chanderi silk is genuine and the zari embroidery doesn't prick the skin at all. Express delivery was within 48 hours.",
    date: "July 28, 2026",
    avatar: "PN"
  },
  {
    name: "Dr. Radhika Iyer",
    city: "Chennai",
    rating: 5,
    verified: true,
    product: "Noor Gulabi Pure Mulmul Cotton Kurti",
    text: "The softest Jaipur mulmul cotton I have ever worn for work. Even after 4 washes, the color has not faded one bit. Truly authentic craftsmanship.",
    date: "July 22, 2026",
    avatar: "RI"
  },
  {
    name: "Sunita Menon",
    city: "Kochi",
    rating: 5,
    verified: true,
    product: "Devika Banarasi Brocade Churidar Suit",
    text: "The peacock teal color is so rich and photogenic! The tissue dupatta gives that ultra-luxe boutique feel without burning a hole in the pocket. 10/10 recommendation.",
    date: "August 4, 2026",
    avatar: "SM"
  }
];

// Size Chart Data (in inches and cm)
const REJI_SIZE_CHART = {
  inches: [
    { size: "XS", bust: "32-34", waist: "26-28", hip: "36-38", kurtiLen: "44", churidarInseam: "38-42" },
    { size: "S", bust: "35-36", waist: "29-30", hip: "39-40", kurtiLen: "45", churidarInseam: "38-42" },
    { size: "M", bust: "37-38", waist: "31-32", hip: "41-42", kurtiLen: "45", churidarInseam: "39-43" },
    { size: "L", bust: "39-41", waist: "33-35", hip: "43-45", kurtiLen: "46", churidarInseam: "39-43" },
    { size: "XL", bust: "42-44", waist: "36-38", hip: "46-48", kurtiLen: "46", churidarInseam: "40-44" },
    { size: "XXL", bust: "45-47", waist: "39-41", hip: "49-51", kurtiLen: "47", churidarInseam: "40-44" },
    { size: "3XL", bust: "48-50", waist: "42-44", hip: "52-54", kurtiLen: "47", churidarInseam: "40-44" }
  ],
  cm: [
    { size: "XS", bust: "81-86", waist: "66-71", hip: "91-96", kurtiLen: "112", churidarInseam: "96-107" },
    { size: "S", bust: "89-91", waist: "74-76", hip: "99-102", kurtiLen: "114", churidarInseam: "96-107" },
    { size: "M", bust: "94-96", waist: "79-81", hip: "104-107", kurtiLen: "114", churidarInseam: "99-109" },
    { size: "L", bust: "99-104", waist: "84-89", hip: "109-114", kurtiLen: "117", churidarInseam: "99-109" },
    { size: "XL", bust: "107-112", waist: "91-96", hip: "117-122", kurtiLen: "117", churidarInseam: "102-112" },
    { size: "XXL", bust: "114-119", waist: "99-104", hip: "124-130", kurtiLen: "119", churidarInseam: "102-112" },
    { size: "3XL", bust: "122-127", waist: "107-112", hip: "132-137", kurtiLen: "119", churidarInseam: "102-112" }
  ]
};

// Available Promo Codes
const REJI_COUPONS = {
  "REJI20": { discountPercent: 20, description: "Flat 20% Off on First Order", minSpend: 999 },
  "FESTIVE500": { flatDiscount: 500, description: "Flat ₹500 Off on orders above ₹2,999", minSpend: 2999 },
  "SILK10": { discountPercent: 10, description: "10% Extra Off on Pure Silk & Velvet Sets", minSpend: 1500 }
};

// Currency Rates relative to INR (base = 1)
const CURRENCIES = {
  INR: { symbol: "₹", name: "INR", rate: 1.0, flag: "🇮🇳" },
  USD: { symbol: "$", name: "USD", rate: 0.012, flag: "🇺🇸" },
  GBP: { symbol: "£", name: "GBP", rate: 0.0094, flag: "🇬🇧" },
  AED: { symbol: "AED ", name: "AED", rate: 0.044, flag: "🇦🇪" },
  EUR: { symbol: "€", name: "EUR", rate: 0.011, flag: "🇪🇺" }
};
